<html>
<head>
<title>FORUM</title>

<LINK REL=STYLESHEET TYPE="text/css" HREF="forum_styles.css">

</head>

<body> 

<table width="90%" align="center" border="0" cellpadding="0" cellspacing="0">
<tr><td>

<h2>PHP6/MySQL Forum</h2>

<table width="50%" border="0" cellpadding="0" cellspacing="0">
<tr>
    <td>
Information:
<br>
<a href="README">README</a>
<br>
<a href="ChangeLog">ChangeLog</a>
<br>
    </td>
    <td>
Download: 
<br>
<a href="forum_2_0_11.tgz">forum_2_0_11.tgz</a>
<br>
<a href="forum_2_0_11.zip">forum_2_0_11.zip</a>
    </td>
</tr>
</table>

<center><h3>Forum demo</h3></center>
<a href="admin.php">Administration demo</a> (login: admin, password: change_it)

