<?

$msg["author"] = "Author";
$msg["date"]   = "Date";
$msg["subject"]   = "Subject";

$msg["msg_text"]  = "Message text";
$msg["send_msg"] = "Send message";
$msg["reset_msg"] = "Clear message";
$msg["orig_msg_text"] = "Quote original text";
$msg["cancel"] = " Cancel ";

$msg["new_thread"] = "Create message in new thread";
$msg["your_msg_new_subject"] = "Your message";
$msg["your_msg_on_subject"] = "Your message in thread ";

$msg["close_win"] = "Close window";
$msg["full_list"] = "All articles";

$msg["continue_thread"] = "Reply";
$msg["open_subthread"]  = "Create subthread";

$msg["name"] = "Your name";
$msg["enter_name"] = "Please enter your name";
$msg["enter_subj"] = "Please enter subject of the message";

$msg["view_article"] = "View article";

$msg["all"] = "all";
$msg["view_articles_for_last"] = "View articles for the last";
$msg["days"] = "days";
$msg["go"] = " Go ";

$msg["all_articles"] = "All articles";

$msg["remote_host"] = "Remote Host";
$msg["remote_addr"] = "Remote IP address";
$msg["proxy_addr"]  = "Address behind proxy";

$msg["search"] = "Search";

$msg["any"] = "any";
$msg["all"] = "all";
$msg["exact"] = "exact";
$msg["keywords"] = "Keywords";

$msg["tot_found"] = "Total records found";

$msg["stats"] = "Stats";
$msg["noread"] = "Nobody has read";

$msg["ch_timeframe"] = "Change timeframe";
$msg["st_date"] = "Start date";
$msg["en_date"] = "End date";
$msg["tot_vis"] = "Total visits";
$msg["host"] = "Host";
$msg["date_visit"] = "Date";

$msg["back"] = "Back";

$msg["views"] = "Views";

$msg["all_thread_articles"] = "View all articles in thread";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>